wx:
  mp:
    configs:
      - appId: wx40d294a89bcd9fcb
        secret: e48b8b33730cb8bf7ed2aa26e671549b
        token: zhongchi
        aesKey: HbQ8Z0VJjGXgc5AmyuBMpqmDDj2YJJgNEPVFrDbjoZ2

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

spring:  profiles:    active:    - mongodb


upload:
  savedir: E:/
  imgpath: upload/images/
  kinderitor: upload/kinderitor/
  ueditor: upload/ueditor/
#图片列表配置
  ueditordir: E:/upload
 
 
 
 
 
 